# Use root/example as user/password credentials
# version: '3.1'

services:

  mongo:
    image: mongo:latest
    healthcheck:
      test: ["CMD-SHELL", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always
    # ports:
    #   - 27017:27017
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: carsaledb
      MONGO_INITDB_ROOT_USERNAME: carusr
      MONGO_INITDB_ROOT_PASSWORD: carpwd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: carusr
      ME_CONFIG_MONGODB_ADMINPASSWORD: carpwd
      ME_CONFIG_MONGODB_URL: mongodb://carusr:carpwd@mongo:27017/
      ME_CONFIG_BASICAUTH: 0

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    restart: always
    ports:
      - 8080:80
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      PRIVATE_KEY: a332f14f4119884157002784c31
      MONGODB_URL: mongodb://carusr:carpwd@mongo:27017/carsalesdb
      API_PORT: 80

  proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - 9090:80
    depends_on:
      - api

volumes:
  db-data: